import rawCountries from "@/data/countries.json";
import type{ActorKind,CohortState,CountryState,DecisionOverride,DecisionSummary,Flow,ScenarioInput,SimulationFrame,SimulationResult}from"./types";
type Raw={code:string;name:string;population:number;lat:number;lng:number;region:string;subregion:string};const countries=(rawCountries as Raw[]).filter(c=>c.population>0);
function rng(seed:number){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let r=Math.imul(t^t>>>15,1|t);r^=r+Math.imul(r^r>>>7,61|r);return((r^r>>>14)>>>0)/4294967296}}
function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0}export const clamp=(x:number)=>Math.max(0,Math.min(1,x));
export function agentCount(pop:number){return Math.max(3,Math.min(100,Math.round(pop/10_000_000)))}
const sectors=["services","industry","agriculture","energy","technology"] as const;
function ruleAction(kind:ActorKind,p:number){if(kind==="government")return p>.66?"targeted intervention":p>.38?"mitigate and monitor":"monitor";if(kind==="business")return p>.66?"change suppliers and output":p>.38?"pass through or absorb costs":"maintain operations";return p>.66?"cut discretionary spending":p>.38?"adapt consumption":"maintain routine"}
export function actionEffect(kind:ActorKind,action:string){const a=action.toLowerCase();if(kind==="government")return a.includes("broad")?.24:a.includes("targeted")?.18:a.includes("mitigate")?.12:.03;if(kind==="business")return a.includes("supplier")?.16:a.includes("absorb")?.08:a.includes("maintain")?.02:.05;return a.includes("alternative")?.14:a.includes("cut")?.12:a.includes("adapt")?.08:.02}
function makeCohorts(c:Raw,seed:number):CohortState[]{const r=rng(seed+hash(c.code)),n=agentCount(c.population),m=new Map<string,CohortState>();for(let i=0;i<n;i++){const kind:ActorKind=i===0?"government":i%8===0?"business":"household",x=r(),income=x<.38?"low":x<.84?"middle":"high",urban=r()<(.48+(hash(c.region)%25)/100),sector=sectors[Math.floor(r()*sectors.length)],id=`${kind}-${income}-${urban?"urban":"rural"}-${sector}`,weight=c.population/n,resilience=clamp(.2+(income==="high"?.35:income==="middle"?.18:0)+r()*.35);const old=m.get(id);if(old){old.weight+=weight;old.share=old.weight/c.population}else m.set(id,{id,kind,income,urban,sector,weight,share:weight/c.population,resilience,exposure:0,pressure:0,action:"maintain",confidence:.5,rationale:"Initial state",decisionSource:"rules",actionEffect:.02})}return[...m.values()]}
function baseExposure(c:Raw,f:string){return clamp(.35+(hash(c.code+f)%45)/100+(f==="energy"&&["Europe","Asia"].includes(c.region)?.1:0)+(f==="climate"&&["Africa","Oceania"].includes(c.region)?.12:0))}
function cohortExposure(x:CohortState,f:string,base:number){let k=1;if(x.income==="low")k+=.15;if(!x.urban&&f==="climate")k+=.18;if(x.sector==="energy"&&f==="energy")k+=.3;if(x.sector==="industry"&&["trade","energy"].includes(f))k+=.2;if(x.sector==="technology"&&f==="technology")k+=.3;if(x.kind==="government")k*=.7;return clamp(base*k)}
function summarize(cs:CohortState[]):DecisionSummary[]{return(["household","business","government"] as ActorKind[]).map(actor=>{const xs=cs.filter(x=>x.kind===actor),total=xs.reduce((a,x)=>a+x.weight,0)||1,groups=new Map<string,number>();xs.forEach(x=>groups.set(x.action,(groups.get(x.action)||0)+x.weight));const[a,w]=[...groups].sort((x,y)=>y[1]-x[1])[0]||["maintain",0];return{actor,action:a,share:w/total,rationale:`Population-weighted from ${xs.length} demographic/sector cohorts.`}})}
function flows(states:CountryState[],family:string):Flow[]{const out:Flow[]=[];for(const a of states){const candidates=states.filter(b=>b.code!==a.code).map(b=>({b,regional:b.region===a.region?1:0,distance:Math.abs(b.lat-a.lat)+Math.abs(b.lng-a.lng),economic:Math.sqrt(a.population*b.population)/1e9})).sort((x,y)=>(y.regional-x.regional)||(x.distance-y.distance)).slice(0,3);for(const {b,regional,economic} of candidates)out.push({from:a.code,to:b.code,strength:clamp(.04+regional*.05+economic*.1),kind:family==="energy"?"energy":family==="trade"?"trade":"regional"})}return out}
export function initializeWorld(s:ScenarioInput):CountryState[]{return countries.map(c=>{const cohorts=makeCohorts(c,s.seed);return{...c,pressure:0,householdStrain:0,productionPressure:0,policyResponse:0,agents:agentCount(c.population),cohorts,decisions:summarize(cohorts),imports:clamp(.25+(hash(c.code+"i")%55)/100),exports:clamp(.2+(hash(c.code+"e")%55)/100),energyExposure:clamp(.2+(hash(c.code+"n")%65)/100),adaptiveCapacity:clamp(.25+(hash(c.code+"capacity")%60)/100)}})}
export function makeFlows(states:CountryState[],family:string){return flows(states,family)}
export function makeFrame(week:number,states:CountryState[],fs:Flow[]):SimulationFrame{const total=states.reduce((a,c)=>a+c.population,0);return{week,countries:states,flows:fs,globalPressure:states.reduce((a,c)=>a+c.pressure*c.population,0)/total,globalHouseholdStrain:states.reduce((a,c)=>a+c.householdStrain*c.population,0)/total,globalProductionPressure:states.reduce((a,c)=>a+c.productionPressure*c.population,0)/total}}
export function stepWorld(prev:CountryState[],s:ScenarioInput,week:number,fs:Flow[],overrides:DecisionOverride[]=[]):CountryState[]{const pressure=new Map(prev.map(x=>[x.code,x.pressure])),overrideMap=new Map(overrides.map(o=>[`${o.countryCode}:${o.cohortId}`,o]));return prev.map(c=>{const raw=countries.find(x=>x.code===c.code)!,base=baseExposure(raw,s.family),target=s.targetRegions?.length&&!s.targetRegions.includes(c.region)?.42:1,shock=s.severity/100*target*Math.exp(-week/Math.max(4,s.durationWeeks*1.45)),incoming=fs.filter(f=>f.to===c.code).reduce((a,f)=>a+(pressure.get(f.from)||0)*f.strength,0),adapt=Math.min(.55,week/Math.max(1,s.durationWeeks)*(.22+c.adaptiveCapacity*.25));const cohorts=c.cohorts.map(x=>{const ex=cohortExposure(x,s.family,base),priorMitigation=x.actionEffect||0,rawPressure=x.pressure*.3+(shock*ex+incoming*.18)*(1-adapt)*(1-x.resilience*.28),p=clamp(rawPressure*(1-priorMitigation));const override=overrideMap.get(`${c.code}:${x.id}`),a=override?.action||ruleAction(x.kind,p),effect=override?.effect??actionEffect(x.kind,a);return{...x,exposure:ex,pressure:p,action:a,confidence:override?.confidence??clamp(.52+Math.abs(p-.5)*.55),rationale:override?.rationale??`${x.income} income · ${x.urban?"urban":"rural"} · ${x.sector}; exposure ${(ex*100).toFixed(0)}%, resilience ${(x.resilience*100).toFixed(0)}%.`,decisionSource:override?"jev" as const:"rules" as const,actionEffect:effect}});const weighted=(kind?:ActorKind)=>{const xs=kind?cohorts.filter(x=>x.kind===kind):cohorts,t=xs.reduce((a,x)=>a+x.weight,0)||1;return xs.reduce((a,x)=>a+x.pressure*x.weight,0)/t};return{...c,cohorts,pressure:weighted(),householdStrain:weighted("household"),productionPressure:weighted("business"),policyResponse:clamp(weighted("government")*(.45+week/s.durationWeeks*.4)),decisions:summarize(cohorts)}})}
export function runSimulation(s:ScenarioInput):SimulationResult{let states=initializeWorld(s);const fs=makeFlows(states,s.family),frames=[makeFrame(0,states,fs)];for(let week=1;week<=s.durationWeeks;week++){states=stepWorld(states,s,week,fs);frames.push(makeFrame(week,states,fs))}return{scenario:s,frames,providerMode:"deterministic",methodology:"WorldSim uses weighted demographic/sector cohorts inside every country. Cohort exposure, resilience and prior decisions affect subsequent state. International links propagate pressure. Numerical mechanics are deterministic for a seed; Jev can replace bounded cohort decisions in provider-enabled runs. Simulation outputs are scenarios, not forecasts."}}
export function compareResults(a:SimulationResult,b:SimulationResult){const af=a.frames.at(-1)!,bf=b.frames.at(-1)!;return bf.countries.map(c=>{const old=af.countries.find(x=>x.code===c.code);return{code:c.code,name:c.name,delta:c.pressure-(old?.pressure??0)}}).sort((x,y)=>Math.abs(y.delta)-Math.abs(x.delta))}
export function continueFromFrame(parent:SimulationResult,s:ScenarioInput,branchWeek:number,overridesByWeek:Map<number,DecisionOverride[]>=new Map()):SimulationResult{const at=Math.max(0,Math.min(branchWeek,parent.frames.length-1));let states=structuredClone(parent.frames[at].countries),fs=makeFlows(states,s.family);const frames=parent.frames.slice(0,at+1).map(f=>structuredClone(f));for(let week=at+1;week<=s.durationWeeks;week++){states=stepWorld(states,s,week,fs,overridesByWeek.get(week)||[]);frames.push(makeFrame(week,states,fs))}return{scenario:s,frames,providerMode:"deterministic",methodology:`Branched from parent simulation at week ${at}. State before the branch is preserved; subsequent state uses the branch scenario and assumptions. ${parent.methodology}`}}
